"""Core data models for the trading system."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from .types import Side, OrderType, SignalType


@dataclass
class Bar:
    """A single OHLCV bar."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    signal_type: SignalType
    price: float
    timestamp: datetime
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    size: Optional[float] = None  # Position size (units or fraction)
    metadata: dict = field(default_factory=dict)


@dataclass
class Order:
    """An order to be submitted to the broker/exchange."""
    symbol: str
    side: Side
    order_type: OrderType
    quantity: float
    price: Optional[float] = None  # None for market orders
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timestamp: Optional[datetime] = None
    order_id: Optional[str] = None


@dataclass
class Fill:
    """A filled order."""
    order_id: str
    symbol: str
    side: Side
    quantity: float
    fill_price: float
    timestamp: datetime
    commission: float = 0.0


@dataclass
class Position:
    """An open position."""
    symbol: str
    side: Side
    entry_price: float
    quantity: float
    entry_time: datetime
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    unrealized_pnl: float = 0.0

    def update_pnl(self, current_price: float) -> None:
        """Update unrealized PnL based on current price."""
        if self.side == Side.BUY:
            self.unrealized_pnl = (current_price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - current_price) * self.quantity


@dataclass
class Trade:
    """A completed trade (entry + exit)."""
    symbol: str
    side: Side
    entry_price: float
    exit_price: float
    quantity: float
    entry_time: datetime
    exit_time: datetime
    pnl: float
    commission: float = 0.0
    exit_reason: str = ""

    @property
    def return_pct(self) -> float:
        """Return as a percentage."""
        if self.side == Side.BUY:
            return (self.exit_price - self.entry_price) / self.entry_price
        return (self.entry_price - self.exit_price) / self.entry_price

    @property
    def is_winner(self) -> bool:
        return self.pnl > 0
